version: "3.8"

services:
  db:
    image: postgres
    container_name: sensoric_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - sensoric_data:/var/lib/postgresql/data

volumes:
  sensoric_data:
