import "./globals.css";

export const metadata = {
  title: "Modular Home Automation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex justify-center items-start">
        {children}
      </body>
    </html>
  );
}
